### ISSUE TITLE
Make a base loader class for every loader type.

### ISSUE THREAD

**Issue by BasicallyIAmFox** [aeterna-gh/QuasarFramework#2]
** THE WHAT **
Reduce amount of code duplication in [loader types](https://github.com/aeterna-gh/QuasarFramework/tree/master/Loaders).

** THE HOW **
```
public abstract class QuasarLoader<T> : ILoadable {
  public IEnumerable<T> Content => ModContent.GetContent<T>();
  public int Count { get; }
  
  public virtual int Add(T type);
  
  public T Get(int index);
  
  public virtual void Load(Mod mod);
  
  public virtual void Unload();
}

public sealed class AbilityLoader : QuasarLoader<Ability>;
public sealed class ElementLoader : QuasarLoader<Element>;
public sealed class FactionLoader : QuasarLoader<Faction>;
public sealed class QRarityLoader : QuasarLoader<QuasarRarity>;
public sealed class SpecializationLoader : QuasarLoader<Specialization>;
public sealed class TraitLoader : QuasarLoader<Trait>;
```

** THE WHY **
Reduces code duplication.

** ADDITIONALS (OPTIONAL) **
Make all loader types public.

**Comment by aeterna-gh** [comment]
I've considered doing this every now and again but I never really saw the point. Keeping them separated seemed more beneficial.

I'll look into the implementation a bit later today.

**Comment by aeterna-gh** [comment]
```cs
namespace QuasarFramework.Loaders
{
    public abstract class QuasarLoader<T> where T : ModType
    {
        public static IEnumerable<T> Content = _content;

        private static readonly List<T> _content = new();

        public static int Count => _content.Count;

        public static int Add(T type)
        {
            int count = Count;
            _content.Add(type);
            return count;
        }

        public static T Get(int index) => index < 0 || index >= _content.Count ? null : _content[index];

        public static bool TryGet(int index, out T instance)
        {
            if (index < 0 || index >= _content.Count)
            {
                instance = null;
                return false;
            }
            instance = _content[index];
            return true;
        }

        public static void Load()
        {

        }

        public static void Unload()
        {
            _content.Clear();
        }
    }

    public sealed class AbilityLoader : QuasarLoader<Ability> { }
    ```
    
    This is the implementation me, Gabe, David and LolXD agreed on. I'll commit with this later if this suits your implementation.

**Comment by BasicallyIAmFox** [comment]
> This is the implementation me, Gabe, David and LolXD agreed on. If you have any changes do suggest them.
> 
> ```cs
> namespace QuasarFramework.Loaders
> {
>     public abstract class QuasarLoader<T> where T : ModType
>     {
>         public static IEnumerable<T> Content = _content;
> 
>         private static readonly List<T> _content = new();
> 
>         public static int Count => _content.Count;
> 
>         public static int Add(T type)
>         {
>             int count = Count;
>             _content.Add(type);
>             return count;
>         }
> 
>         public static T Get(int index) => index < 0 || index >= _content.Count ? null : _content[index];
> 
>         public static bool TryGet(int index, out T instance)
>         {
>             if (index < 0 || index >= _content.Count)
>             {
>                 instance = null;
>                 return false;
>             }
>             instance = _content[index];
>             return true;
>         }
> 
>         public static void Load()
>         {
> 
>         }
> 
>         public static void Unload()
>         {
>             _content.Clear();
>         }
>     }
>     
>     public sealed class AbilityLoader : QuasarLoader<Ability> { }
> }
> ```

what's the reason for making `Load` and `Unload` static?

**Comment by aeterna-gh** [comment]
> what's the reason for making `Load` and `Unload` static?

Calling them in `QuasarFramework.cs` required obj refs and I was too lazy to implement them. That and there's no real ulterior loading I think I need right now. It's more of a "ignore now worry later" issue.

**Comment by BasicallyIAmFox** [comment]
> > what's the reason for making `Load` and `Unload` static?
> 
> Calling them in `QuasarFramework.cs` required obj refs and I was too lazy to implement them. That and there's no real ulterior loading I think I need right now. It's more of a "ignore now worry later" issue.

ah fair enough
